### ISSUE TITLE
NetBackup StorageClass Implementation

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/OpenShift4-RollOut#155]
Implement NetApp and Netbackup Integrated storageClass for the cluster

- [x] Deploy test implementation in Labs
- [x] Determine physical storage commitment in production NetApp as per Steven's comment below (15%? 20%?)
- [x] Initial documentation for "How to Request a Restore"

**Comment by jefkel** [comment]
(Content added from original message to track decision requirements)
Fr: Steven
>
Hello Todd and Stephanie
Jeff has asked me to look into our options for connecting NetBackup to NetApp for the OCP 4 build. I had a call with our NetApp experts and think we now have a plan for how to move forward.
NetBackup can be pointed at either the whole NetApp, or a pattern matched set of volumes. To accomplish this we’d want to have all the volumes created on the NetApp for the backup storage class to have a unique prefix.
Trident backends can specify a storagePrefix to use when creating volumes, along with the driver (NFS or ISCSI) and StorageVM they connect to. We want to be able to target a backend to ensure we get the right storagePrefix per storage class.
K8s Storage Classes can specify which driver and storage pools they match up with, but not which Trident backend directly.
This makes it a little hard to get a storage class to match to a specific Trident backend. ie: if two Trident backends have the same driver like ontap-nas-economy the storage class will try and create new volumes on either of them. So our plan is to create two different SVMs with different storagePools available, and use that feature of the storage class to ensure the right storagePrefix is used.
We also want to use the full FlexVols and not the economy mode, so that we can enable snapshots. This gives people some self-serve access to quickly recover very recent versions. The downside with full FlexVols is the limit on how many we can have, which is why we’ve been leaning on the economy mode so far. A 2 node NetApp can support a maximum of 2000 FlexVols.
I think we should be safe using full FlexVols for backup. Currently we have 50 nfs-backup volumes to nearly 1600 file volumes and 200 block volumes. If that ratio maintains as we grow into the OCP 4 prod cluster we should have no issues staying below 2000 FlexVols.
I think the bigger issue is going to be setting up the storagePools. A storagePool is a set of disks in the NetApp and needs to be configured on initial setup of the NetApp when we get them. The prod NetApp in Kamloops is likely going to have 24 disks per node and we’ll need to decide how to divvy them up between regular storage and backup storage.
We could start with using less than the full 24 disks, and add spares into whichever storagePool needs more capacity as we grow. But this will affect performance by having fewer disks to spread the IOPS across and there is some performance penalty when we add a disk and the RAID rebalances.
We currently have about 2TB in nfs-backup and 15T in the rest of the storage classes. Do you expect more users to take advantage of a backup storage class in the future?
We don’t have to make any decisions today, but should start thinking about how we want to allocate disks to a backup storage class, and if we expect to be creating a lot of these and might need to stick to economy mode instead of full FlexVols for backup storage PVs.

**Comment by StevenBarre** [comment]
While working on the LUN ID issue today, I leaned that I can in fact target a Storage Class to a specific backend without needing separate Aggregates. The `storagePools` parameter can take wildcards of just the backend name. https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-gold-regex.yaml#L7

I've tested this in CLAB and was able to get different volume prefixes without needing separate aggregates. So it looks like we no longer need to make a decision around disk allocations.

I think we still need to make a decision around Economy Mode vs full FlexVols.

**Comment by StevenBarre** [comment]
Decided that we won't worry about splitting the disks into two aggregates given the new info.
Decided that we will start with netapp-backup-standard running on NFS Economy mode as its unlikely people will need self serve snapshots and preserving FlexVols will be important in the new system.

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-ops/pull/253
