### ISSUE TITLE
Create Platform Services Azure Cluster Design & Initial Deploy

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#24]
We will need a cluster design for Azure some high level items to determine.
- [x] Azure SP Account
- [x] Azure regions and zones
- [x] DNS Name & Azure DNS config
- [x] Azure Network decisions
- [x] VM sizing & count decisions 
- [x] VM disk sizing
- [x] Cluster storage options 
- [x] Pull secret

**Comment by tosazuwa** [comment]
Hi @filiy , can you add details to this ticket

**Comment by filiy** [comment]
Details are above in check-list form.

Just adding in some files to the repo today

**Comment by filiy** [comment]
Azure readme file has been updated: 
https://github.com/BCDevOps/OpenShift4-RollOut/blob/openshift4-azure/openshift4-azure/openshit4-azure-readme.md

Waiting on:
Dan - DNS subdomain delegation
Pull Secret - I'll grab this from Todd or Gov team
SP Account - I don't have permissions to create SP. Will need to track down Azure AD gov admin to create.

**Comment by StevenBarre** [comment]
@filiy I can get you a pull secret

**Comment by filiy** [comment]
Got the pull secret from Steve! Thanks! 
Dan also got the DNS record updated!

```
;; AUTHORITY SECTION:
clearwater.devops.gov.bc.ca. 299 IN	SOA	ns1-07.azure-dns.com. azuredns-hostmaster.microsoft.com. 1 3600 300 2419200 300
```

Just need to get the SP account created now

**Comment by filiy** [comment]
SP Account created with Todd's help.

Waiting to get permissions enabled for the SP as Todd does not have access to this.

**Comment by filiy** [comment]
- Updates to Azure set up, a new RG has been set up and SP is created. Waiting for internet access in Azure to get sorted

- I need to look into the https cert and see if the Azure LB will support it, or I can load it on the nodes
- Look into infrastructure nodes if needed or just master and worker nodes?

**Comment by tosazuwa** [comment]
network blocker for Azure is removed - phil.arctiq should be good to go. If he needs help from hosting branch Jonathan McCaig <Jon.McCaig@gov.bc.ca> is the contact

**Comment by filiy** [comment]
More testing has been completed. Due to Azure being locked down there are some issues with the ocp4 installer. Email sent to Jon.McCaig.:

> - Microsoft.ManagedIdentity resource provider needs to be enabled for OpenShift 4 in Azure and it's currently disabled in the BCGov-MGD-CLNPD1 subscription.
> 
> - The openshift-installer needs to create an RG to install openshift into. I couldn't find a way to tell the installer to use an existing RG. The idea here is that each OCP4 cluster has its own RG with the name format <clustername>-<random 5 characters>-rg and gets terraform state file associated with it. Destroying the cluster will blow away the RG knowing there is nothing non-cluster related in there. Can the SP have permission to create RGs?

Also there seems to be an issue with the SP account. Will need to test some more.

`[phil@c3po ~]$ az login --service-principal --username b819d41f-b8f7-44a9-9837-3e562bccd7d  --password XXXX --tenant 6fdb5200-3d0d-4a8a-b036-d3685e359adc
Get Token request returned http error: 400 and server response: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier 'b819d41f-b8f7-44a9-9837-3e562bccd7d' was not found in the directory '6fdb5200-3d0d-4a8a-b036-d3685e359adc'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\r\nTrace ID: 1612714d-81e5-4b9b-bb40-33189a0ce300\r\nCorrelation ID: 6310aa8c-b7fc-40c3-96c2-c4730b0bf095\r\nTimestamp: 2020-01-13 16:02:08Z","error_codes":[700016],"timestamp":"2020-01-13 16:02:08Z","trace_id":"1612714d-81e5-4b9b-bb40-33189a0ce300","correlation_id":"6310aa8c-b7fc-40c3-96c2-c4730b0bf095","error_uri":"https://login.microsoftonline.com/error?code=700016"}`

Considering this blocked until Jon gets back to me. I will test a few more items in our lab.

**Comment by filiy** [comment]
I'm able to successful deploy and configure OCP 4 on Azure in the `DevOps Platform Services` subscription. Still haven't heard back from Jon about the other subscription. 

Tested the Azure File storage class options and documented. Updated readme & arch docs pushed.

Destroying cluster for today.

**Comment by filiy** [comment]
I would say this is unblocked. I've been able to deploy/destroy the cluster twice now in Azure. The OG RG Todd set up is working. Still waiting to hear back from Jon about the RG he set up.

I will keep using the working RG for now to test.

Working on post cluster config now for adding in infra machine set and moving "infa" objects onto the new cluster.

https://docs.openshift.com/container-platform/4.2/machine_management/creating-infrastructure-machinesets.html#infrastructure-moving-router_creating-infrastructure-machinesets

Latest code/docs pushed to branch.
