### ISSUE TITLE
SG - OCP 4 Platform - Shared Image Management

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#290]
Platform Services has imported or built images that development teams may rely on.  These images need to be documented with appropriate update schedules and build/deploy/import pipelines for deployment and synchronization across multiple clusters.

This Epic will Track the progress of the image management tasks.

Definition of Done
All Plaform managed images in OpenShift 4 will be identified with automated update processes in place.

The 2 initial locations for investigation are the images in the *openshift* and *bcgov, bcgov-tools* namespaces in the current cluster.

**Sync this work with the BCGov custom image review and update in Platform Experience Backlog**
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/579

**Comment by mitovskaol** [comment]
Need to document the decisions in this ticket and include the teams impact section.

Recommend to provide an overview of the impact at the next Sprint Review on Sep 29

**Comment by jleach** [comment]
Notes from Meeting on 2020-09-11

- Need to figure out how to integrate CICD with Aqua; no Aqua on Day 1.
- Image versioning sample: `patroni-postgres-96:v1.1`; We will, in general, follow RHs name and version format (ie https://catalog.redhat.com/software/containers/rhel8/postgresql-96/5ba0ad1f5a134643ef2eeb9d).
- Jeff / Cailey: Req. meeting to hammer out life custom image life cycle:
 - - How long will we keep a version around? Clecio suggests max 3.
 - - How do we engage the community to take over image management if *they* want additional features such as update to patronie. We'll maintain CICD pipeline and distribution.
- Should not advertise that we have `imagestreamtag` sync enabled. We *may* require teams to use Artifactory for pulling in external images.
- Need to look into how supporting images are used for builds (ie S2I) so the cluster can build if the external images are unavailable. (ref. Image: registry.redhat.io/openshift3/ose-docker-builder:v3.11.232).
- Images in `openshift` namespace required for the cluster:
     cli
     cli-artifacts
     installer
     installer-artifacts
     must-gather
     oauth-proxy
     tests
     tools
- Do we need to do anything for Jenkins to work?
- We would like to optimize templates so that they play nice on the cluster.
- Remove Jenkins from catalog and make ours avail from `bcgov` which may or may not be changed; the template will be for sure.
- Our existing pipeline: https://jenkins-bcgov-tools.pathfinder.gov.bc.ca/

**Comment by jleach** [comment]
Some suggested images we could offer the community:

1. Patroni
2. Container backup image
3. Jenkins
4. NATS
5. minio
