### ISSUE TITLE
Aporeto installation on KLAB

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#303]
**Describe the issue**
Aporeto is required to be installed on KLAB with all enforcement policies verified. 

**Which Sprint Goal is this issue related to?**

**Additional context**

**Definition of done Checklist (where applicable)**
- [x] Aporeto installed
- [x] Aporeto Operator installed
- [x] All tests passed (specify what kind of testing is done) *Detail to be added for tests/validation required*

**Comment by j-pye** [comment]
Aporeto Testing included the following tasks:
- Test Developer and Operations Builds - This lead to the use of the PodInjectorSelect which allows us to inject an init container so pods wait until they are protected before trying to start up and run the desired container applications.
- Test Namespace to Namespace communication - Policies must exist in both namespaces in order for an accepted flow to be established
- Test Internal Namespace communication
    - Pod to Any other Pod in the Namespace
    - Any Pod to Any Pod in the Namespace
    - Zero Trust - No policies, All rejections
- Test Access to K8s API - In order to support `must-gather` which creates a new namespace, all namespaces are given access to the k8s api for free. (This includes builds)
- Route Ingress - The `openshift-ingress` namespace was included to accomplish this. The act of creating a route is the security policy needed to enable external communication to a pod. No additional policies are required so long as the Pod / Service is up
- Health Checks - Additional policy was created at the Cluster Namespace level to enable health checks. Testing was done with both Readiness and Liveness probes with TCP Checks, HTTP Checks, and Command Execution checks.
