### ISSUE TITLE
Klab Resource Allocation

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/OpenShift4-RollOut#346]
**Describe the issue**
KLAB currently has 8 app nodes with 4 cores each. After system reservations and the many daemonsets, there isn't much room for actual workloads.

As we migrate the VMs from the old ESX Pathfinder cluster to the new Dell based ESX cluster, there is much more capacity for larger VMs.

We'll decomission 4 of the app nodes and scale up the remaining 4 to double their CPU and RAM.

Also double the resources on the Infra nodes so more of the infra tooling (Cluster Metering) can be moved to the infra nodes.

**Definition of done Checklist (where applicable)**
- [x] [Move VMs to new cluster](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/519)
- [x] Increase infra nodes to 8 vCPU / 64G RAM
- [x] Increase 4 app nodes to 8 vCPU / 64G RAM
- [x] iStore order to decommission 4 app nodes

**Comment by wmhutchison** [comment]
Have confirmed the iStore for decommissioning the four APP VMs since we now have suitable RITM tickets for each VM. Have processed the initial "Verify server decommission/QA server decommission" tickets, not yet seen the actual "shutdown OS" tickets drop yet.

**Comment by wmhutchison** [comment]
Some blockers were first hit and over-come:
- bootstrap kept on failing. Engaged network at first who could find nothing amiss. Red Hat then gave us a work-around since the URL fetch for machine config was taking longer than the default 10s. Tweaked automation so ignition files now reflect this as 2m which will become the new default shortlly.
- new ESXi cluster was misssing out-of-cluster connectivity for Storage VLAN. Dan Deane escalated and resolved this with Network team.

Work now performed thus far:
- All replacement APP VMs have been successfully bootstrapped on the new ESXi cluster, which doubles their capacity.
- existing APP VMs meant for decomm have been removed from cluster and powered off. Will proceed with decomm on Monday morning if there's no reason seen to revert this.
- updated the relevant repo with changes to date so we have accurate master branch info as we do not want certain playbooks ran from the repo in question if inventory MAC addresses do not reflect current reality.

**Comment by wmhutchison** [comment]
All work is complete except for rebuilding the three MASTER nodes. All being well, expecting that to be completed by EOD today, or tomorrow at the latest depending on any possible new wrinkles/issues unique to the master nodes.

**Comment by wmhutchison** [comment]
While CPU counts are accurate, the memory allotments for the replacement APP/INFRA nodes is half what it needs to be. Will coordinate both with VMWare team as well as other stakeholders to get these upgrades done.

**Comment by wmhutchison** [comment]
Have scheduled this with Dan Deane to take place first thing in the morning on Wednesday September 23rd 2020.

**Comment by wmhutchison** [comment]
Work with VMWare now complete, thus concluding this work along with all of the defined check-boxes listed above.
