### ISSUE TITLE
Artifactory Service  Operationalization Part 1

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/OpenShift4-RollOut#415]
Finish the remaining work on finishing the Artifactory implementation (i.e. private repo feature).
@caggles can you please add individual relevant tickets as dependencies to this Sprint Goal.

**Comment by caggles** [comment]
Hi @mitovskaol ! I'm going to close this ticket as there are more granular tickets for this task in the developer-experience repo - since MVP has been reached, I would no longer consider the operationalization of Artifactory to be part of the OCP4 rollout. The remaining tickets here will be related only to fresh roll-outs on new OCP4 clusters!
