### ISSUE TITLE
Update DNS record for chat.developer.gov.bc.ca

### ISSUE THREAD

**Issue by jleach** [BCDevOps/OpenShift4-RollOut#455]
Looks like my idea for #454 won't work because the domains don't match for the certificate `ERR_CERT_COMMON_NAME_INVALID`. Are you able to update `chat.developer.gov.bc.ca` to point to the OCP311 Pathfinder cluster? Thx. I think I'll get everyone to start using the new domain for RC then migrate the app.

**Comment by StevenBarre** [comment]
Well its CNAMEd currently to `chat.pathfinder`, which is just part of `*.pathfinder` so technically it already does point at the v3 cluster.

If you accept the TLS error it currently just gives you the "app not configured" page, since the v3 router doesn't yet have a route for it.

Remember that DNS and HTTP are different layers of the OSI model.

**Comment by jleach** [comment]
Thanks for explaining. I think I was expecting different behaviour but this makes sense. I can configure the route with the proper cert see if that resolves the issue.

J.

**Comment by jleach** [comment]
Will use the existing setup. Thx.
